const state={projects:[],project:null,vehicles:[],section:'overview'};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('theme-toggle').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('brdocs-theme',dark?'light':'dark')});
if(localStorage.getItem('brdocs-theme')==='dark')document.documentElement.dataset.theme='dark';
$('back-projects').addEventListener('click',()=>location.hash='/');
$('docs-nav-links').addEventListener('click',event=>{const button=event.target.closest('[data-section]');if(button&&!button.disabled)showSection(button.dataset.section)});
window.addEventListener('hashchange',route);
async function get(url){const response=await fetch(url);if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return response.json()}
async function boot(){try{state.projects=await get('/api/projects');$('project-status').textContent=`${state.projects.length} projects online`;renderProjects()}catch(error){$('project-status').textContent='Unable to connect';$('project-grid').innerHTML=`<div class="loading-card">${esc(error.message)}. Start the BRDocs server beside the projects.</div>`}route()}
function renderProjects(){$('project-grid').innerHTML=state.projects.map(project=>`<button class="project-card" data-project="${esc(project.name)}"><span class="project-mark">BR</span><h2>${esc(project.name)}</h2><p>${esc(project.description||'BRBuild project documentation')}</p></button>`).join('')||'<div class="loading-card">No sibling folders with BRBuild.yaml were found.</div>';document.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',()=>location.hash=`/project/${encodeURIComponent(card.dataset.project)}`))}
async function route(){const match=location.hash.match(/^#\/project\/([^/]+)(?:\/vehicles)?(?:\/vehicle\/([^/]+))?/);if(!match){$('project-landing').classList.remove('hidden');$('project-docs').classList.add('hidden');return}const name=decodeURIComponent(match[1]);try{if(!state.project||state.project.name!==name){state.project=state.projects.find(project=>project.name===name)||await get(`/api/projects/${encodeURIComponent(name)}`);state.vehicles=await get(`/api/projects/${encodeURIComponent(name)}/vehicles`)}$('project-landing').classList.add('hidden');$('project-docs').classList.remove('hidden');$('nav-project-name').textContent=state.project.name;$('nav-vehicle-count').textContent=state.vehicles.length;showSection(match[2]?'vehicle':location.hash.includes('/vehicles')?'vehicles':'overview',match[2])}catch(error){$('docs-content').innerHTML=`<div class="loading-card">${esc(error.message)}</div>`;$('project-landing').classList.add('hidden');$('project-docs').classList.remove('hidden')}}
function showSection(section,vehicleName){state.section=section;document.querySelectorAll('.nav-link').forEach(button=>button.classList.toggle('active',button.dataset.section===section));if(section==='overview')renderOverview();else if(section==='vehicles')renderVehicles();else if(section==='about')renderAbout();else renderVehicle(vehicleName)}
function renderOverview(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / passenger guide</div><h1>Everything you need to run the railway.</h1><p class="lead">A practical guide to the vehicles, formations and liveries in this GRF. Start with the fleet, then open a unit to see what can be bought and how it is configured.</p><div class="intro-card"><strong>Start here</strong><p>Vehicles are organised as units, with profiles for different formations and liveries for different operators. The game presents each available combination in the purchase list.</p></div><div class="stats-row"><div class="stat"><strong>${state.vehicles.length}</strong><span>documented units</span></div><div class="stat"><strong>${state.vehicles.reduce((sum,v)=>sum+(v.profiles?.length||0),0)}</strong><span>formations</span></div><div class="stat"><strong>${state.vehicles.reduce((sum,v)=>sum+(v.liveries?.length||0),0)}</strong><span>liveries</span></div></div><h2>Fleet at a glance</h2><div class="vehicle-grid">${state.vehicles.slice(0,6).map(vehicleCard).join('')}</div><button class="back-section" style="margin-top:25px" onclick="showSection('vehicles')">View the full fleet →</button>`;bindVehicleCards()}
function vehicleCard(vehicle){return `<article class="vehicle-card" data-vehicle="${esc(vehicle.slug)}"><div class="sprite-wrap">${vehicle.sprite?`<img src="${esc(vehicle.sprite)}" alt="">`:''}</div><div class="vehicle-card-body"><h3>${esc(vehicle.name||vehicle.slug)}</h3><small>${esc(vehicle.sub_name||vehicle.vehicle_type||'Vehicle')}</small><div class="vehicle-meta">${vehicle.speed?`<span class="tag">${esc(vehicle.speed)} mph</span>`:''}${vehicle.power?`<span class="tag">${esc(vehicle.power)} hp</span>`:''}</div></div></article>`}
function bindVehicleCards(){document.querySelectorAll('[data-vehicle]').forEach(card=>card.addEventListener('click',()=>location.hash=`/project/${encodeURIComponent(state.project.name)}/vehicle/${encodeURIComponent(card.dataset.vehicle)}`))}
function renderVehicles(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / fleet</div><h1>The fleet.</h1><p class="lead">Browse every unit in the project. Select a vehicle for its performance, available formations and liveries.</p><div class="vehicle-grid">${state.vehicles.map(vehicleCard).join('')}</div>`;bindVehicleCards()}
function renderAbout(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / using the GRF</div><h1>How the fleet fits together.</h1><p class="lead">The GRF adds vehicles to OpenTTD's purchase lists. Each unit can expose several profiles and liveries, so you can choose the train that fits your route.</p><h2>Units</h2><p>A unit is the top-level entry in the documentation. It usually represents a named class or vehicle family, such as a Class 375. Its base statistics describe the common behaviour shared by its variants.</p><h2>Profiles</h2><p>Profiles describe formations or configurations of the same unit: a 3-car and 4-car multiple unit, for example. Capacity, power, weight and sprite arrangement can change between profiles.</p><h2>Liveries</h2><p>Liveries are paint schemes and operator variants. They normally share a unit's profiles while changing the appearance in the purchase list and on the map.</p><h2>In the game</h2><p>Use the vehicle's introduction date to find it in the purchase list. Filter by the project's compatible rail type, then compare capacity, speed and power for your route.</p>`}
async function renderVehicle(slug){let vehicle=state.vehicles.find(item=>item.slug===slug);if(!vehicle)return renderVehicles();$('docs-content').innerHTML=`<button class="back-section" onclick="location.hash='#/project/${encodeURIComponent(state.project.name)}/vehicles'">← Back to fleet</button><div class="crumb" style="margin-top:28px">${esc(state.project.name)} / vehicle</div><div class="detail-head"><div><h1>${esc(vehicle.name)}</h1><p>${esc(vehicle.sub_name||vehicle.based_on||'')}</p></div></div>${vehicle.sprite?`<div class="detail-sprite"><img src="${esc(vehicle.sprite)}" alt="${esc(vehicle.name)} sprite"></div>`:''}<h2>At a glance</h2><table class="data-table">${[['Vehicle type',vehicle.vehicle_type],['Traction',vehicle.power_type?.join(', ')],['Top speed',vehicle.speed?`${vehicle.speed} mph`:null],['Power',vehicle.power?`${vehicle.power} hp`:null],['Introduced',vehicle.introduction_date]].filter(([,value])=>value).map(([key,value])=>`<tr><td>${esc(key)}</td><td><strong>${esc(value)}</strong></td></tr>`).join('')}</table><h2>Formations</h2><div class="formation-list">${(vehicle.profiles||[]).map(profile=>`<div class="formation"><strong>${esc(profile.name||profile.identifier)}</strong><small>${[profile.num_vehicles&&`${profile.num_vehicles} vehicles`,profile.capacity&&`${profile.capacity} capacity`,profile.power&&`${profile.power} hp`].filter(Boolean).join(' · ')}</small></div>`).join('')||'<p>No profile data published yet.</p>'}</div><h2>Liveries</h2><div class="formation-list">${(vehicle.liveries||[]).map(livery=>`<div class="formation"><strong>${esc(livery.name)}</strong><small>${esc((livery.special_tags||[]).join(' · '))}</small></div>`).join('')||'<p>No alternate liveries published yet.</p>'}</div>`}
boot();
