const state={projects:[],project:null,vehicles:[],section:'overview'};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('theme-toggle').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('brdocs-theme',dark?'light':'dark')});
if(localStorage.getItem('brdocs-theme')==='dark')document.documentElement.dataset.theme='dark';
$('back-projects').addEventListener('click',()=>location.hash='/');
$('docs-nav-links').addEventListener('click',event=>{const button=event.target.closest('[data-section]');if(button&&!button.disabled){const section=button.dataset.section;location.hash=`/project/${encodeURIComponent(state.project.name)}/${section}`}});
window.addEventListener('hashchange',route);
async function get(url){const response=await fetch(url);if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return response.json()}
async function boot(){try{state.projects=await get('/api/projects');renderProjects()}catch(error){$('project-grid').innerHTML=`<div class="loading-card">${esc(error.message)}. The documentation server is unavailable.</div>`}route()}
function renderProjects(){$('project-grid').innerHTML=state.projects.map(project=>`<button class="project-card" data-project="${esc(project.name)}"><span class="project-mark">BR</span><h2>${esc(project.name)}</h2><p>${esc(project.description||'BRTrains group NewGRF')}</p></button>`).join('')||'<div class="loading-card">No BRTrains projects found.</div>';document.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',()=>location.hash=`/project/${encodeURIComponent(card.dataset.project)}`))}
async function route(){const match=location.hash.match(/^#\/project\/([^/]+)(?:\/(overview|vehicles|liveries|about|livery|vehicle)(?:\/([^/]+))?)?/);if(!match){$('project-landing').classList.remove('hidden');$('project-docs').classList.add('hidden');return}const name=decodeURIComponent(match[1]);try{if(!state.project||state.project.name!==name){state.project=state.projects.find(project=>project.name===name)||await get(`/api/projects/${encodeURIComponent(name)}`);state.vehicles=await get(`/api/projects/${encodeURIComponent(name)}/vehicles`)}$('project-landing').classList.add('hidden');$('project-docs').classList.remove('hidden');$('nav-project-name').textContent=state.project.name;$('docs-project-label').textContent=state.project.name;$('nav-vehicle-count').textContent=state.vehicles.length;const section=match[2]||'overview';showSection(section==='vehicle'?'vehicle':section,match[3])}catch(error){$('docs-content').innerHTML=`<div class="loading-card">${esc(error.message)}</div>`;$('project-landing').classList.add('hidden');$('project-docs').classList.remove('hidden')}}
function showSection(section,value){state.section=section;document.querySelectorAll('.nav-link[data-section]').forEach(button=>button.classList.toggle('active',button.dataset.section===section||(section==='livery'&&button.dataset.section==='liveries')));if(section==='overview')renderOverview();else if(section==='vehicles')renderVehicles();else if(section==='liveries')renderLiveries();else if(section==='about')renderAbout();else if(section==='livery')renderLivery(value);else renderVehicle(value)}
function renderOverview(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / overview</div><h1>Welcome to ${esc(state.project.name)}.</h1><p class="lead">Documentation for a BRTrains group NewGRF for OpenTTD. Browse the fleet, compare formations and find the liveries available for each unit.</p><div class="intro-card"><strong>In this guide</strong><p>Units are the named vehicle families. Profiles describe formations and performance variants. Liveries are the operator paint schemes available in the game.</p></div><div class="stats-row"><div class="stat"><strong>${state.vehicles.length}</strong><span>vehicles</span></div><div class="stat"><strong>${state.vehicles.reduce((sum,v)=>sum+(v.profiles?.length||0),0)}</strong><span>formations</span></div><div class="stat"><strong>${allLiveries().length}</strong><span>liveries</span></div></div><h2>Featured vehicles</h2><div class="vehicle-grid">${state.vehicles.slice(0,6).map(vehicleCard).join('')}</div><button class="back-section" style="margin-top:25px" onclick="location.hash='#/project/${encodeURIComponent(state.project.name)}/vehicles'">View all vehicles →</button>`;bindVehicleCards()}
function vehicleCard(vehicle){return `<article class="vehicle-card" data-vehicle="${esc(vehicle.slug)}"><div class="sprite-wrap">${vehicle.sprite?`<img src="${esc(vehicle.sprite)}" alt="">`:''}</div><div class="vehicle-card-body"><h3>${esc(vehicle.name||vehicle.slug)}</h3><small>${esc(vehicle.sub_name||vehicle.vehicle_type||'Vehicle')}</small><div class="vehicle-meta">${vehicle.speed?`<span class="tag">${esc(vehicle.speed)} mph</span>`:''}${vehicle.power?`<span class="tag">${esc(vehicle.power)} hp</span>`:''}</div></div></article>`}
function bindVehicleCards(){document.querySelectorAll('[data-vehicle]').forEach(card=>card.addEventListener('click',()=>location.hash=`/project/${encodeURIComponent(state.project.name)}/vehicle/${encodeURIComponent(card.dataset.vehicle)}`))}
function renderVehicles(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / vehicles</div><h1>The fleet.</h1><p class="lead">Every unit in this project, with its available formations, stats and liveries.</p><div class="vehicle-grid">${state.vehicles.map(vehicleCard).join('')}</div>`;bindVehicleCards()}
function allLiveries(){const byName=new Map();state.vehicles.forEach(vehicle=>(vehicle.liveries||[]).forEach(livery=>{const current=byName.get(livery.name)||{name:livery.name,vehicles:[]};if(!current.vehicles.some(item=>item.slug===vehicle.slug))current.vehicles.push(vehicle);byName.set(livery.name,current)}));return [...byName.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function liveryCard(livery){return `<article class="formation livery-card"><button class="livery-link" data-livery="${esc(livery.name)}"><strong>${esc(livery.name)}</strong><span class="livery-count">${livery.vehicles.length} vehicle${livery.vehicles.length===1?'':'s'}</span></button><span class="livery-arrow">→</span></article>`}
function bindLiveryCards(){document.querySelectorAll('[data-livery]').forEach(card=>card.addEventListener('click',()=>location.hash=`/project/${encodeURIComponent(state.project.name)}/livery/${encodeURIComponent(card.dataset.livery)}`))}
function renderLiveries(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / liveries</div><h1>Liveries.</h1><p class="lead">Operator schemes and paint variants across the fleet. Choose a livery to see every unit that carries it.</p><div class="formation-list">${allLiveries().map(liveryCard).join('')||'<p>No livery data published yet.</p>'}</div>`;bindLiveryCards()}
function renderLivery(name){const livery=allLiveries().find(item=>item.name===name);if(!livery)return renderLiveries();$('docs-content').innerHTML=`<button class="back-section" onclick="location.hash='#/project/${encodeURIComponent(state.project.name)}/liveries'">← All liveries</button><div class="crumb" style="margin-top:28px">${esc(state.project.name)} / livery</div><h1>${esc(livery.name)}</h1><p class="lead">This livery is available on the following units.</p><h2>${livery.vehicles.length} vehicle${livery.vehicles.length===1?'':'s'}</h2><div class="vehicle-grid">${livery.vehicles.map(vehicleCard).join('')}</div>`;bindVehicleCards()}
function renderAbout(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / using the GRF</div><h1>How the fleet fits together.</h1><p class="lead">The GRF adds vehicles to OpenTTD's purchase lists. Each unit can expose several profiles and liveries, so you can choose the train that fits your route.</p><h2>Units</h2><p>A unit is the top-level entry in the documentation. It usually represents a named class or vehicle family. Its base statistics describe the common behaviour shared by its variants.</p><h2>Profiles</h2><p>Profiles describe formations or configurations of the same unit: a 3-car and 4-car multiple unit, for example. Capacity, power, weight and sprite arrangement can change between profiles.</p><h2>Liveries</h2><p>Liveries are paint schemes and operator variants. Select a livery in the sidebar to see every unit that carries it.</p><h2>In the game</h2><p>Use the vehicle's introduction date to find it in the purchase list. Filter by the project's compatible rail type, then compare capacity, speed and power for your route.</p>`}
function renderVehicle(slug){const vehicle=state.vehicles.find(item=>item.slug===slug);if(!vehicle)return renderVehicles();$('docs-content').innerHTML=`<button class="back-section" onclick="location.hash='#/project/${encodeURIComponent(state.project.name)}/vehicles'">← Back to vehicles</button><div class="crumb" style="margin-top:28px">${esc(state.project.name)} / vehicle</div><div class="detail-head"><div><h1>${esc(vehicle.name)}</h1><p>${esc(vehicle.sub_name||vehicle.based_on||'')}</p></div></div>${vehicle.sprite?`<div class="detail-sprite"><img src="${esc(vehicle.sprite)}" alt="${esc(vehicle.name)} sprite"></div>`:''}<h2>At a glance</h2><table class="data-table">${[['Vehicle type',vehicle.vehicle_type],['Traction',vehicle.power_type?.join(', ')],['Top speed',vehicle.speed?`${vehicle.speed} mph`:null],['Power',vehicle.power?`${vehicle.power} hp`:null],['Introduced',vehicle.introduction_date]].filter(([,value])=>value).map(([key,value])=>`<tr><td>${esc(key)}</td><td><strong>${esc(value)}</strong></td></tr>`).join('')}</table><h2>Formations</h2><div class="formation-list">${(vehicle.profiles||[]).map(profile=>`<div class="formation"><strong>${esc(profile.name||profile.identifier)}</strong><small>${[profile.num_vehicles&&`${profile.num_vehicles} vehicles`,profile.capacity&&`${profile.capacity} capacity`,profile.power&&`${profile.power} hp`].filter(Boolean).join(' · ')}</small></div>`).join('')||'<p>No profile data published yet.</p>'}</div><h2>Liveries</h2><div class="formation-list">${(vehicle.liveries||[]).map(livery=>`<div class="formation livery-card"><button class="livery-link" data-livery="${esc(livery.name)}"><strong>${esc(livery.name)}</strong><span class="livery-count">View all vehicles with this livery</span></button><span class="livery-arrow">→</span></div>`).join('')||'<p>No alternate liveries published yet.</p>'}</div>`;bindLiveryCards()}
boot();
