const state={projects:[],project:null,vehicles:[],manifest:null,formationTimers:[],animationSpeed:Number(localStorage.getItem('brdocs-animation-speed'))||900,section:'overview'};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const systemTheme=()=>window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';
const applyTheme=(theme,choice=theme)=>{document.documentElement.dataset.theme=theme==='dark'?'dark':'';document.querySelectorAll('[data-theme-choice]').forEach(button=>button.classList.toggle('active',button.dataset.themeChoice===choice))};
const savedTheme=localStorage.getItem('brdocs-theme-override');
const selectedTheme=savedTheme||'system';
applyTheme(selectedTheme==='system'?systemTheme():selectedTheme,selectedTheme);
document.querySelectorAll('[data-theme-choice]').forEach(button=>button.addEventListener('click',()=>{const choice=button.dataset.themeChoice;if(choice==='system')localStorage.removeItem('brdocs-theme-override');else localStorage.setItem('brdocs-theme-override',choice);applyTheme(choice==='system'?systemTheme():choice,choice)}));
const themeMedia=window.matchMedia?.('(prefers-color-scheme: dark)');
themeMedia?.addEventListener?.('change',()=>{if(!localStorage.getItem('brdocs-theme-override'))applyTheme(systemTheme(),'system')});
$('back-projects').addEventListener('click',()=>location.hash='/');
$('docs-nav-links').addEventListener('click',event=>{const button=event.target.closest('[data-section]');if(button&&!button.disabled){const section=button.dataset.section;location.hash=`/project/${encodeURIComponent(state.project.name)}/${section}`}});
window.addEventListener('hashchange',route);
async function get(url){const response=await fetch(url);if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return response.json()}
async function boot(){try{state.projects=await get('/api/projects');renderProjects()}catch(error){$('project-grid').innerHTML=`<div class="loading-card">${esc(error.message)}. The documentation server is unavailable.</div>`}route()}
function renderProjects(){$('project-grid').innerHTML=state.projects.map(project=>`<button class="project-card" data-project="${esc(project.name)}"><span class="project-mark">BR</span><h2>${esc(project.name)}</h2><p>${esc(project.description||'BRTrains group NewGRF')}</p></button>`).join('')||'<div class="loading-card">No BRTrains projects found.</div>';document.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',()=>location.hash=`/project/${encodeURIComponent(card.dataset.project)}`))}
async function route(){const match=location.hash.match(/^#\/project\/([^/]+)(?:\/(overview|vehicles|liveries|about|livery|vehicle)(?:\/([^/]+))?)?/);if(!match){$('project-landing').classList.remove('hidden');$('project-docs').classList.add('hidden');return}const name=decodeURIComponent(match[1]);try{if(!state.project||state.project.name!==name){state.project=state.projects.find(project=>project.name===name)||await get(`/api/projects/${encodeURIComponent(name)}`);state.vehicles=await get(`/api/projects/${encodeURIComponent(name)}/vehicles`);state.manifest=await get(`/api/projects/${encodeURIComponent(name)}/manifest`).catch(()=>null)}$('project-landing').classList.add('hidden');$('project-docs').classList.remove('hidden');$('nav-project-name').textContent=state.project.name;$('docs-project-label').textContent=state.project.name;$('nav-vehicle-count').textContent=state.vehicles.length;$('nav-livery-count').textContent=allLiveries().length;const section=match[2]||'overview';const value=match[3]?decodeURIComponent(match[3]):undefined;showSection(section==='vehicle'?'vehicle':section,value)}catch(error){$('docs-content').innerHTML=`<div class="loading-card">${esc(error.message)}</div>`;$('project-landing').classList.add('hidden');$('project-docs').classList.remove('hidden')}}
function showSection(section,value){if(section!=='vehicle')state.formationTimers.splice(0).forEach(clearInterval);document.querySelectorAll('.nav-link[data-section]').forEach(button=>button.classList.toggle('active',button.dataset.section===section||(section==='livery'&&button.dataset.section==='liveries')));if(section==='overview')renderOverview();else if(section==='vehicles')renderVehicles();else if(section==='liveries')renderLiveries();else if(section==='about')renderAbout();else if(section==='livery')renderLivery(value);else renderVehicle(value)}
function renderOverview(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / overview</div><h1>Welcome to ${esc(state.project.name)}.</h1><p class="lead">Documentation for a BRTrains group NewGRF for OpenTTD. Browse the fleet, compare formations and find the liveries available for each unit.</p><div class="intro-card"><strong>In this guide</strong><p>Units are the named vehicle families. Profiles describe formations and performance variants. Liveries are the operator paint schemes available in the game.</p></div><div class="stats-row"><div class="stat"><strong>${state.vehicles.length}</strong><span>vehicles</span></div><div class="stat"><strong>${state.vehicles.reduce((sum,v)=>sum+(v.profiles?.length||0),0)}</strong><span>formations</span></div><div class="stat"><strong>${allLiveries().length}</strong><span>liveries</span></div></div><button class="back-section" style="margin-top:25px" onclick="location.hash='#/project/${encodeURIComponent(state.project.name)}/vehicles'">Browse all vehicles →</button>`}
function vehicleCard(vehicle){const preview=formationVariants(vehicle)[0];return `<article class="vehicle-card" data-vehicle="${esc(vehicle.slug)}"><div class="sprite-wrap">${preview?`<canvas class="vehicle-thumbnail" data-thumbnail-vehicle="${esc(vehicle.slug)}" width="1" height="1"></canvas><span class="thumbnail-loading">Rendering…</span>`:vehicle.sprite?`<img src="${esc(vehicle.sprite)}" alt="">`:''}</div><div class="vehicle-card-body"><h3>${esc(vehicle.name||vehicle.slug)}</h3><small>${esc(vehicle.sub_name||vehicle.vehicle_type||'Vehicle')}</small><div class="vehicle-meta">${vehicle.speed?`<span class="tag">${esc(vehicle.speed)} mph</span>`:''}${vehicle.power?`<span class="tag">${esc(vehicle.power)} hp</span>`:''}</div></div></article>`}
function bindVehicleCards(){document.querySelectorAll('[data-vehicle]').forEach(card=>card.addEventListener('click',()=>location.hash=`/project/${encodeURIComponent(state.project.name)}/vehicle/${encodeURIComponent(card.dataset.vehicle)}`))}
function vehicleMatches(vehicle,query,type,liveryQuery){const haystack=[vehicle.name,vehicle.slug,vehicle.sub_name,vehicle.based_on,vehicle.vehicle_type,...(vehicle.power_type||[])].filter(Boolean).join(' ').toLowerCase();const liveryNames=(vehicle.liveries||[]).map(item=>item.name).join(' ').toLowerCase();return(!query||haystack.includes(query))&&(!type||vehicle.vehicle_type===type)&&(!liveryQuery||liveryNames.includes(liveryQuery))}
function renderVehicleResults(){const query=$('vehicle-search').value.trim().toLowerCase(),type=$('vehicle-type-filter').value,liveryQuery=$('vehicle-livery-search').value.trim().toLowerCase(),filtered=state.vehicles.filter(vehicle=>vehicleMatches(vehicle,query,type,liveryQuery));$('vehicle-results').innerHTML=filtered.map(vehicleCard).join('')||'<div class="loading-card">No vehicles match these filters.</div>';$('vehicle-result-count').textContent=`${filtered.length} of ${state.vehicles.length}`;bindVehicleCards();bindThumbnailCanvases()}
function renderVehicles(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / vehicles</div><h1>The fleet.</h1><p class="lead">Every unit in this project, with its available formations, stats and liveries.</p><div class="filter-bar vehicle-filter-bar"><div class="filter-row"><input id="vehicle-search" class="filter-input" type="search" placeholder="Search vehicles, classes or operators"><select id="vehicle-type-filter" class="filter-select"><option value="">All vehicle types</option>${[...new Set(state.vehicles.map(vehicle=>vehicle.vehicle_type).filter(Boolean))].sort().map(type=>`<option value="${esc(type)}">${esc(type)}</option>`).join('')} </select><span id="vehicle-result-count" class="result-count"></span></div><div class="filter-row livery-filter-row"><label for="vehicle-livery-search">Livery</label><input id="vehicle-livery-search" class="filter-input" type="search" placeholder="Search by livery name, e.g. Southeastern"></div></div><div id="vehicle-results" class="vehicle-grid"></div>`;$('vehicle-search').addEventListener('input',renderVehicleResults);$('vehicle-type-filter').addEventListener('change',renderVehicleResults);$('vehicle-livery-search').addEventListener('input',renderVehicleResults);renderVehicleResults()}
function allLiveries(){const byName=new Map();state.vehicles.forEach(vehicle=>(vehicle.liveries||[]).forEach(livery=>{const current=byName.get(livery.name)||{name:livery.name,vehicles:[]};if(!current.vehicles.some(item=>item.slug===vehicle.slug))current.vehicles.push(vehicle);byName.set(livery.name,current)}));return [...byName.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function liveryCard(livery){return `<article class="formation livery-card"><button class="livery-link" data-livery="${esc(livery.name)}"><strong>${esc(livery.name)}</strong><span class="livery-count">${livery.vehicles.length} vehicle${livery.vehicles.length===1?'':'s'}</span></button><span class="livery-arrow">→</span></article>`}
function bindLiveryCards(){document.querySelectorAll('[data-livery]').forEach(card=>card.addEventListener('click',()=>location.hash=`/project/${encodeURIComponent(state.project.name)}/livery/${encodeURIComponent(card.dataset.livery)}`))}
function liveryMatches(livery,query){return!query||[livery.name,...livery.vehicles.map(vehicle=>vehicle.name)].join(' ').toLowerCase().includes(query)}
function renderLiveryResults(){const query=$('livery-search').value.trim().toLowerCase(),sort=$('livery-sort').value,filtered=allLiveries().filter(livery=>liveryMatches(livery,query)).sort((a,b)=>sort==='size'?b.vehicles.length-a.vehicles.length:a.name.localeCompare(b.name));$('livery-results').innerHTML=filtered.map(liveryCard).join('')||'<div class="loading-card">No liveries match these filters.</div>';$('livery-result-count').textContent=`${filtered.length} of ${allLiveries().length}`;bindLiveryCards()}
function renderLiveries(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / liveries</div><h1>Liveries.</h1><p class="lead">Operator schemes and paint variants across the fleet. Choose a livery to see every unit that carries it.</p><div class="filter-bar"><input id="livery-search" class="filter-input" type="search" placeholder="Search liveries or vehicles"><select id="livery-sort" class="filter-select"><option value="name">Sort alphabetically</option><option value="size">Most vehicles first</option></select><span id="livery-result-count" class="result-count"></span></div><div id="livery-results" class="formation-list"></div>`;$('livery-search').addEventListener('input',renderLiveryResults);$('livery-sort').addEventListener('change',renderLiveryResults);renderLiveryResults()}
function renderLivery(name){const livery=allLiveries().find(item=>item.name===name);if(!livery)return renderLiveries();$('docs-content').innerHTML=`<button class="back-section" onclick="location.hash='#/project/${encodeURIComponent(state.project.name)}/liveries'">← All liveries</button><div class="crumb" style="margin-top:28px">${esc(state.project.name)} / livery</div><h1>${esc(livery.name)}</h1><p class="lead">This livery is available on the following units.</p><h2>${livery.vehicles.length} vehicle${livery.vehicles.length===1?'':'s'}</h2><div class="vehicle-grid">${livery.vehicles.map(vehicleCard).join('')}</div>`;bindVehicleCards();bindThumbnailCanvases()}
function renderAbout(){$('docs-content').innerHTML=`<div class="crumb">${esc(state.project.name)} / using the GRF</div><h1>How the fleet fits together.</h1><p class="lead">The GRF adds vehicles to OpenTTD's purchase lists. Each unit can expose several profiles and liveries, so you can choose the train that fits your route.</p><h2>Units</h2><p>A unit is the top-level entry in the documentation. It usually represents a named class or vehicle family. Its base statistics describe the common behaviour shared by its variants.</p><h2>Profiles</h2><p>Profiles describe formations or configurations of the same unit: a 3-car and 4-car multiple unit, for example. Capacity, power, weight and sprite arrangement can change between profiles.</p><h2>Liveries</h2><p>Liveries are paint schemes and operator variants. Select a livery in the sidebar to see every unit that carries it.</p><h2>In the game</h2><p>Use the vehicle's introduction date to find it in the purchase list. Filter by the project's compatible rail type, then compare capacity, speed and power for your route.</p>`}
function formationVariants(vehicle){if(!state.manifest)return[];return state.manifest.variants.filter(item=>item.vehicle?.identifier===vehicle.identifier||item.vehicle?.name===vehicle.name)}
function assetUrl(pathValue){return pathValue?`/api/projects/${encodeURIComponent(state.project.name)}/asset/${pathValue.path.split('/').map(encodeURIComponent).join('/')}`:null}
function formationCard(item,index){const label=[item.profile?.name||item.profile?.identifier,item.livery?.name].filter(Boolean).join(' · ')||item.variant?.identifier||`Formation ${index+1}`;return `<article class="formation-preview"><div class="formation-preview-head"><strong>${esc(label)}</strong><small>${item.formation?.part_count||item.variant?.articulated_count?`${esc(item.formation?.part_count||item.variant.articulated_count)} vehicles`:'Single vehicle'}</small></div><div class="formation-canvas-wrap"><canvas data-formation-index="${index}" width="1" height="1"></canvas><span class="formation-loading">Rendering formation…</span></div><div class="view-picker" data-view-picker="${index}"><button type="button" data-auto class="active">Auto</button>${Array.from({length:8},(_,view)=>`<button type="button" data-view="${view}">${view+1}</button>`).join('')}</div><div class="speed-picker" aria-label="Animation speed"><span>Speed</span><button type="button" data-speed="5400" aria-label="Slow">&gt;</button><button type="button" data-speed="2700" aria-label="Medium">&gt;&gt;</button><button type="button" data-speed="900" aria-label="Fast">&gt;&gt;&gt;</button></div></article>`}
function renderFormation(item,canvas,view){const formation=item.formation||item.variant?.formation,host=canvas.closest('.formation-canvas-wrap')||canvas.parentElement;if(!formation?.sprite_pattern||!item.spritesets?.length){host?.classList.add('formation-unavailable');return}const pattern=formation.sprite_pattern,parts=pattern.map(number=>item.spritesets[number-1]);if(parts.some(part=>!part))return;const rows=parts.map(part=>part.rows?.[view]);if(rows.some(row=>!row))return;const sources=new Map();Promise.all(parts.map(part=>{const url=assetUrl(part.file);if(sources.has(url))return Promise.resolve();const image=new Image();image.src=url;return new Promise((resolve,reject)=>{image.onload=()=>{sources.set(url,image);resolve()};image.onerror=reject})})).then(()=>{const scale=2,gap=2,top=Math.min(...rows.map(row=>row.offset_y)),bottom=Math.max(...rows.map(row=>row.offset_y+row.height)),positions=[];let cursor=0;rows.forEach(row=>{positions.push(cursor);cursor+=row.width+gap});const left=Math.min(...rows.map((row,index)=>positions[index]+row.offset_x)),right=Math.max(...rows.map((row,index)=>positions[index]+row.offset_x+row.width)),width=right-left;canvas.width=width*scale;canvas.height=(bottom-top)*scale;const context=canvas.getContext('2d');context.imageSmoothingEnabled=false;rows.forEach((row,index)=>{const part=parts[index],image=sources.get(assetUrl(part.file));const sx=(part.x||0)+row.left_x,sy=(part.y||0)+row.upper_y,drawX=positions[index]+row.offset_x-left;context.drawImage(image,sx,sy,row.width,row.height,drawX*scale,(row.offset_y-top)*scale,row.width*scale,row.height*scale);const pixels=context.getImageData(drawX*scale,(row.offset_y-top)*scale,row.width*scale,row.height*scale),data=pixels.data;for(let i=0;i<data.length;i+=4){const white=data[i]===255&&data[i+1]===255&&data[i+2]===255,blue=data[i]===0&&data[i+1]===0&&data[i+2]===255;if(white||blue)data[i+3]=0}context.putImageData(pixels,drawX*scale,(row.offset_y-top)*scale)});host.querySelector('.formation-loading,.thumbnail-loading')?.remove()}).catch(()=>{const loading=host.querySelector('.formation-loading,.thumbnail-loading');if(loading)loading.textContent='Image unavailable'})}
function bindThumbnailCanvases(){document.querySelectorAll('[data-thumbnail-vehicle]').forEach(canvas=>{const vehicle=state.vehicles.find(item=>item.slug===canvas.dataset.thumbnailVehicle),variant=vehicle&&formationVariants(vehicle)[0];if(variant)renderFormation(variant,canvas,6)})}
function setAnimationSpeed(speed){state.animationSpeed=Number(speed);localStorage.setItem('brdocs-animation-speed',String(state.animationSpeed));document.querySelectorAll('[data-speed]').forEach(button=>button.classList.toggle('active',Number(button.dataset.speed)===state.animationSpeed))}
function bindFormationCanvases(){document.querySelectorAll('[data-formation-index]').forEach(canvas=>{const item=formationVariants(state.vehicles.find(vehicle=>vehicle.slug===state.currentVehicleSlug)||{})[Number(canvas.dataset.formationIndex)];if(!item)return;const card=canvas.closest('.formation-preview'),picker=card.querySelector('.view-picker'),auto=picker.querySelector('[data-auto]'),viewButtons=[...picker.querySelectorAll('[data-view]')],speedButtons=[...card.querySelectorAll('[data-speed]')];let view=6,automatic=true;const mark=()=>{auto.classList.toggle('active',automatic);viewButtons.forEach(button=>button.classList.toggle('active',!automatic&&Number(button.dataset.view)===view));speedButtons.forEach(button=>button.classList.toggle('active',Number(button.dataset.speed)===state.animationSpeed))};const draw=()=>renderFormation(item,canvas,view);const schedule=()=>{const timer=setTimeout(()=>{state.formationTimers=state.formationTimers.filter(item=>item!==timer);if(automatic){view=(view+1)%8;draw()}schedule()},state.animationSpeed);state.formationTimers.push(timer)};auto.addEventListener('click',()=>{automatic=true;mark();draw()});viewButtons.forEach(button=>button.addEventListener('click',()=>{automatic=false;view=Number(button.dataset.view);mark();draw()}));speedButtons.forEach(button=>button.addEventListener('click',()=>{setAnimationSpeed(button.dataset.speed);mark()}));mark();draw();schedule()})}
function renderVehicle(slug){state.formationTimers.splice(0).forEach(clearInterval);const vehicle=state.vehicles.find(item=>item.slug===slug);if(!vehicle)return renderVehicles();state.currentVehicleSlug=slug;const variants=formationVariants(vehicle);$('docs-content').innerHTML=`<button class="back-section" onclick="location.hash='#/project/${encodeURIComponent(state.project.name)}/vehicles'">← Back to vehicles</button><div class="crumb" style="margin-top:28px">${esc(state.project.name)} / vehicle</div><div class="detail-head"><div><h1>${esc(vehicle.name)}</h1><p>${esc(vehicle.sub_name||vehicle.based_on||'')}</p></div></div>${vehicle.sprite?`<div class="detail-sprite"><img src="${esc(vehicle.sprite)}" alt="${esc(vehicle.name)} sprite"></div>`:''}<h2>At a glance</h2><table class="data-table">${[['Vehicle type',vehicle.vehicle_type],['Traction',vehicle.power_type?.join(', ')],['Top speed',vehicle.speed?`${vehicle.speed} mph`:null],['Power',vehicle.power?`${vehicle.power} hp`:null],['Introduced',vehicle.introduction_date]].filter(([,value])=>value).map(([key,value])=>`<tr><td>${esc(key)}</td><td><strong>${esc(value)}</strong></td></tr>`).join('')}</table><h2>Formations</h2><div class="formation-previews">${variants.map(formationCard).join('')||'<p>No materialised formation data published yet.</p>'}</div><h2>Liveries</h2><div class="formation-list">${(vehicle.liveries||[]).map(livery=>`<div class="formation livery-card"><button class="livery-link" data-livery="${esc(livery.name)}"><strong>${esc(livery.name)}</strong><span class="livery-count">View all vehicles with this livery</span></button><span class="livery-arrow">→</span></div>`).join('')||'<p>No alternate liveries published yet.</p>'}</div>`;bindLiveryCards();bindFormationCanvases()}
boot();
