import { createServer } from 'node:http';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const ROOT = path.resolve(process.env.BRDOCS_ROOT || path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT || 4173);
const COMMONS_CACHE = path.resolve(process.env.BRDOCS_CACHE || path.join(SITE, '.cache', 'commons'));
const COMMONS_API = 'https://commons.wikimedia.org/w/api.php';
const COMMONS_CACHE_TTL = 24 * 60 * 60 * 1000;
const text = value => String(value ?? '').split('#',1)[0].trim().replace(/^['"]|['"]$/g, '');
const lines = source => source.replace(/\r/g, '').split('\n');
const scalar = (source, key) => { const match = lines(source).find(line => new RegExp(`^\\s{2}${key}:`).test(line)); return match ? text(match.slice(match.indexOf(':') + 1).split(' #')[0]) : ''; };
const list = (source, key) => { const result=[]; const rows=lines(source); const start=rows.findIndex(line=>line.trim()===`${key}:`); if(start<0)return result; for(let i=start+1;i<rows.length&&/^\s{4}- /.test(rows[i]);i++)result.push(text(rows[i].replace(/^\s{4}- /,''))); return result; };
const block = (source, name) => { const rows=lines(source), start=rows.findIndex(row=>row.trim()===`${name}:`); if(start<0)return ''; const out=[]; for(let i=start+1;i<rows.length;i++){if(rows[i]&&/^\S/.test(rows[i]))break;out.push(rows[i])} return out.join('\n'); };
const inlineList = value => { const match=String(value||'').match(/^\[(.*)\]$/); return match ? match[1].split(',').map(text).filter(Boolean) : (value ? [text(value)] : []); };
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderCommonsMarkup(value){const anchors=[];const tokenized=String(value||'').replace(/<a\b[^>]*\bhref\s*=\s*["'](https?:\/\/[^"'<>]+)["'][^>]*>([\s\S]*?)<\/a>/gi,(_,href,label)=>{const token=`\u0000${anchors.length}\u0000`;anchors.push(`<a href="${escapeHtml(href)}" target="_blank" rel="noreferrer">${escapeHtml(label.replace(/<[^>]*>/g,''))}</a>`);return token;});let output=escapeHtml(tokenized.replace(/<[^>]*>/g,''));anchors.forEach((anchor,index)=>{output=output.replace(`\u0000${index}\u0000`,anchor);});return output;}
function isOpenLicense(value){const license=String(value||'').trim().toLowerCase();if(/\bcc\s*by(?:-sa)?-(?:nc|nd)\b/.test(license)||license.includes('noncommercial')||license.includes('no derivatives'))return false;return /^cc\s*(by|by-sa)(?:[- ]|$)/.test(license)||/^cc0(?:[- ]|$)/.test(license)||license.includes('public domain')||license.startsWith('pd-');}
function selectCommonsImage(pages){for(const page of pages||[]){const info=page.imageinfo?.[0],metadata=info?.extmetadata||{},license=metadata.LicenseShortName?.value||metadata.License?.value;if(isOpenLicense(license)&&(info?.thumburl||info?.url))return{title:page.title,sourceUrl:`https://commons.wikimedia.org/wiki/${encodeURIComponent(page.title.replaceAll(' ','_'))}`,url:info.thumburl||info.url,license:String(license).trim(),licenseUrl:metadata.LicenseUrl?.value||'',artistHtml:renderCommonsMarkup(metadata.Artist?.value||metadata.Credit?.value||'')};}return null;}
const cacheKey=(project,slug)=>crypto.createHash('sha256').update(`${project}:${slug}`).digest('hex');
async function readCommonsCache(key){try{const record=JSON.parse(await read(path.join(COMMONS_CACHE,`${key}.json`)));if(Date.now()-record.checkedAt<COMMONS_CACHE_TTL)return record;}catch{}return null;}
async function commonsImage(project,vehicle){const key=cacheKey(project.name,vehicle.slug),cached=await readCommonsCache(key);if(cached)return cached.image?{...cached.image,artistHtml:cached.image.artistHtml||renderCommonsMarkup(cached.image.artist||''),imageUrl:`/api/projects/${encodeURIComponent(project.name)}/vehicle/${encodeURIComponent(vehicle.slug)}/commons/image`}:null;let image=null;try{const query=[vehicle.name,vehicle.based_on].filter(Boolean).join(' ');const params=new URLSearchParams({action:'query',format:'json',origin:'*',generator:'search',gsrsearch:query,gsrnamespace:'6',gsrlimit:'10',prop:'imageinfo',iiprop:'url|extmetadata',iiurlwidth:'1600'});const response=await fetch(`${COMMONS_API}?${params}`);if(!response.ok)throw new Error(`Commons returned ${response.status}`);const data=await response.json();image=selectCommonsImage(Object.values(data.query?.pages||{}));if(image){const download=await fetch(image.url);const type=download.headers.get('content-type')||'';if(!download.ok||!type.startsWith('image/')||Number(download.headers.get('content-length')||0)>15_000_000)throw new Error('Commons image download was not a supported image');const extension=type.includes('png')?'png':type.includes('webp')?'webp':'jpg';await fs.mkdir(COMMONS_CACHE,{recursive:true});await fs.writeFile(path.join(COMMONS_CACHE,`${key}.${extension}`),Buffer.from(await download.arrayBuffer()));image={...image,extension};}}catch(error){console.warn(`Wikimedia Commons lookup failed for ${vehicle.name}: ${error.message}`);}await fs.mkdir(COMMONS_CACHE,{recursive:true});await fs.writeFile(path.join(COMMONS_CACHE,`${key}.json`),JSON.stringify({checkedAt:Date.now(),image}));return image?{...image,imageUrl:`/api/projects/${encodeURIComponent(project.name)}/vehicle/${encodeURIComponent(vehicle.slug)}/commons/image`}:null;}
const profiles = source => { const start=source.indexOf('\nprofiles:'); if(start<0)return []; const end=source.indexOf('\nliveries:',start); const section=source.slice(start,end<0?source.length:end); const result=[]; for(const [index,row] of section.split('\n').entries()){if(!/^  - /.test(row))continue; const following=section.split('\n').slice(index,index+20).join('\n'); result.push({identifier:scalar(following,'identifier'),name:scalar(following,'name'),num_vehicles:scalar(following,'num_vehicles'),capacity:scalar(following,'capacity'),power:scalar(following,'power')})} return result; };
const liveries = source => { const start=source.indexOf('\nliveries:'); if(start<0)return []; const section=source.slice(start); return section.split('\n').filter(row=>/^  - name:/.test(row)).map(row=>({name:text(row.split(':').slice(1).join(':')),special_tags:[]})); };
async function read(file){return fs.readFile(file,'utf8')}
async function projectEntries(){const entries=await fs.readdir(ROOT,{withFileTypes:true}); const projects=[]; for(const entry of entries){if(!entry.isDirectory()||entry.name.startsWith('.'))continue; try{const manifest=await read(path.join(ROOT,entry.name,'BRBuild.yaml')); if(!manifest.includes('BRBuild.yaml')&& !/^project:/m.test(manifest))continue; const project=block(manifest,'project'); if(scalar(project,'docs').toLowerCase()!=='true')continue; const grf=await read(path.join(ROOT,entry.name,'src/grf/GRF.yaml')).catch(()=> ''); projects.push({name:entry.name,description:scalar(block(grf,'grf'),'description')||'BRTrains group NewGRF',path:entry.name,targetFolders:list(project,'target_folders'),purchaseList:purchaseListSetting(grf)})}catch{}} return projects.sort((a,b)=>a.name.localeCompare(b.name));}
function purchaseListSetting(grf){const section=block(grf,'purchase_list');return {order:scalar(section,'order')||null,file:scalar(section,'file')||null}}
async function orderVehicles(project,vehicles){const grf=await read(path.join(ROOT,project.name,'src/grf/GRF.yaml')).catch(()=> '');const setting=purchaseListSetting(grf);const manifest=await read(path.join(ROOT,project.name,'docs/generated/manifest.json')).then(JSON.parse).catch(()=>null);const byIdentifier=new Map(vehicles.map(vehicle=>[vehicle.identifier,vehicle]));if(setting.file&&manifest){const source=await read(path.join(ROOT,project.name,'src/grf',setting.file)).catch(()=> '');const order=[];const seen=new Set();for(const line of source.split(/\r?\n/)){const match=line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*,?\s*$/);if(!match)continue;const variant=manifest.variants.find(item=>item.variant?.identifier===match[1]);const identifier=variant?.vehicle?.identifier;if(identifier&&!seen.has(identifier)){seen.add(identifier);order.push(identifier)}}return [...order,...vehicles.filter(vehicle=>!seen.has(vehicle.identifier)).map(vehicle=>vehicle.identifier).sort()].map(identifier=>byIdentifier.get(identifier)).filter(Boolean)}const mode=setting.order||'none';if(mode==='none'&&manifest){const ids=new Map();for(const item of manifest.variants||[]){const id=item.vehicle?.identifier,sprite=item.sprite_id?.id;if(id&&Number.isFinite(sprite)&&(!ids.has(id)||sprite<ids.get(id)))ids.set(id,sprite)}return vehicles.slice().sort((a,b)=>(ids.get(a.identifier)??Number.MAX_SAFE_INTEGER)-(ids.get(b.identifier)??Number.MAX_SAFE_INTEGER))}const facts=new Map((manifest?.vehicles||[]).map(vehicle=>[vehicle.identifier,vehicle]));const date=value=>{const match=String(value||'').match(/(\d{4})-(\d{2})-(\d{2})/);return match?Date.UTC(+match[1],+match[2]-1,+match[3]):Number.MAX_SAFE_INTEGER};const classMatch=name=>String(name||'').match(/^Class\s+(\d+)(?:\s*\/\s*(\d+))?/i);const key=vehicle=>{const fact=facts.get(vehicle.identifier)||vehicle;if(mode==='date'||mode==='none')return [date(fact.introduction_date),String(fact.name||'').toLowerCase()];const type=String(fact.train_type||'').toLowerCase();const match=classMatch(fact.name);const group=type==='coach'?3:type==='wagon'?4:match?2:1;return [group,match?Number(match[1]):0,match&&match[2]?Number(match[2]):0,date(fact.introduction_date),String(fact.name||'').toLowerCase()]};return vehicles.slice().sort((a,b)=>{const ak=key(a),bk=key(b);for(let index=0;index<ak.length;index++){if(ak[index]<bk[index])return-1;if(ak[index]>bk[index])return 1}return 0})}
async function findVehicles(project){const result=[]; for(const folder of project.targetFolders.length?project.targetFolders:['src/vehicles']){const root=path.join(ROOT,project.name,folder); await walk(root,async file=>{if(!file.endsWith('.yaml')||file.endsWith('GRF.yaml'))return; const source=await read(file); const rel=path.relative(path.join(ROOT,project.name),file).replaceAll(path.sep,'/'); const dir=path.dirname(rel); const slug=path.basename(file,'.yaml'); const info=block(source,'info'), stats=block(source,'stats'), dates=block(source,'dates'); const image=await findImage(path.dirname(file),slug); result.push({slug,identifier:scalar(info,'identifier')||slug,name:scalar(info,'name')||slug,sub_name:scalar(info,'sub_name'),based_on:scalar(info,'based_on'),vehicle_type:scalar(stats,'vehicle_type'),power_type:list(stats,'power_type'),speed:scalar(stats,'speed'),power:scalar(stats,'power'),introduction_date:scalar(dates,'introduction_date'),profiles:profiles(source),liveries:liveries(source),sprite:image?`/api/projects/${encodeURIComponent(project.name)}/asset/${encodeURIComponent(relDir(image,project.name))}`:null,path:rel,dir})})} return orderVehicles(project,result);}
function relDir(file,project){return path.relative(path.join(ROOT,project),file).replaceAll(path.sep,'/')}
async function findImage(dir,slug){for(const name of [`${slug}.png`,`${slug}_24px.png`]){try{await fs.access(path.join(dir,name));return path.join(dir,name)}catch{}}return null}
async function walk(dir,visit){let entries;try{entries=await fs.readdir(dir,{withFileTypes:true})}catch{return}for(const entry of entries){if(entry.name==='ingested'||entry.name==='new'||entry.name==='error'||entry.name.startsWith('.'))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())await walk(full,visit);else await visit(full)}}
function send(res,status,body,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(type==='application/json'?JSON.stringify(body):body)}
function safeProject(value){return value && !value.includes('/') && !value.includes('\\') && !value.includes('..')}
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`); const parts=url.pathname.split('/').filter(Boolean); if(parts[0]==='api'&&parts[1]==='projects'){const projects=await projectEntries();if(parts.length===2)return send(res,200,projects);const name=decodeURIComponent(parts[2]);if(!safeProject(name)||!projects.some(project=>project.name===name))return send(res,404,{error:'Project not found'});const project=projects.find(item=>item.name===name);if(parts[3]==='vehicles')return send(res,200,await findVehicles(project));if(parts[3]==='vehicle'&&parts[5]==='commons'){const slug=decodeURIComponent(parts[4]||'');if(!safeProject(slug))return send(res,404,{error:'Vehicle not found'});const vehicle=(await findVehicles(project)).find(item=>item.slug===slug);if(!vehicle)return send(res,404,{error:'Vehicle not found'});const key=cacheKey(project.name,vehicle.slug),record=await readCommonsCache(key);if(parts[6]==='image'){if(!record?.image?.extension)return send(res,404,{error:'Commons image unavailable'});const file=path.join(COMMONS_CACHE,`${key}.${record.image.extension}`);const data=await fs.readFile(file);return send(res,200,data,`image/${record.image.extension==='jpg'?'jpeg':record.image.extension}`)}return send(res,200,await commonsImage(project,vehicle));}if(parts[3]==='manifest'){const file=path.join(ROOT,name,'docs/generated/manifest.json');try{return send(res,200,JSON.parse(await read(file)))}catch(error){return send(res,404,{error:`Build manifest unavailable: ${error.message}`})}}if(parts[3]==='asset'){const relative=decodeURIComponent(parts.slice(4).join('/'));const file=path.resolve(ROOT,name,relative);if(!file.startsWith(path.resolve(ROOT,name)+path.sep)||!file.endsWith('.png'))return send(res,403,{error:'Asset denied'});const data=await fs.readFile(file);return send(res,200,data,'image/png')}} const requested=parts.length?parts.join('/'): 'index.html';const file=path.resolve(SITE,requested);if(!file.startsWith(SITE+path.sep))return send(res,403,{error:'Denied'});const data=await fs.readFile(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};return send(res,200,data,types[path.extname(file)]||'application/octet-stream')}catch(error){send(res,500,{error:error.message})}});
if (process.argv[1] === fileURLToPath(import.meta.url)) server.listen(PORT, "127.0.0.1", () => console.log(`BRDocs serving ${ROOT} at http://127.0.0.1:${PORT}`));

export { isOpenLicense, selectCommonsImage, renderCommonsMarkup };
